# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mediaplayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mediaPlayerWidget = QtWidgets.QWidget(self.centralwidget)
        self.mediaPlayerWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mediaPlayerWidget.sizePolicy().hasHeightForWidth())
        self.mediaPlayerWidget.setSizePolicy(sizePolicy)
        self.mediaPlayerWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mediaPlayerWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mediaPlayerWidget.setObjectName("mediaPlayerWidget")
        self.verticalLayout_2.addWidget(self.mediaPlayerWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currentTime = QtWidgets.QLabel(self.centralwidget)
        self.currentTime.setMinimumSize(QtCore.QSize(60, 0))
        self.currentTime.setStyleSheet("color: rgb(255, 255, 255);")
        self.currentTime.setAlignment(QtCore.Qt.AlignCenter)
        self.currentTime.setObjectName("currentTime")
        self.horizontalLayout.addWidget(self.currentTime)
        self.timeSlider = QtWidgets.QSlider(self.centralwidget)
        self.timeSlider.setEnabled(False)
        self.timeSlider.setStyleSheet("QSlider::groove:horizontal { \n"
"    background-color: white;\n"
"    border: 0px solid #424242; \n"
"    height: 10px; \n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::handle:horizontal { \n"
"    background-color: dark-blue; \n"
"    border: 2px solid rgb(118, 253, 248); \n"
"    width: 16px; \n"
"    height: 20px; \n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius:10px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover { \n"
"    border-radius: 10px;\n"
"}")
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.horizontalLayout.addWidget(self.timeSlider)
        self.totalTime = QtWidgets.QLabel(self.centralwidget)
        self.totalTime.setMinimumSize(QtCore.QSize(60, 0))
        self.totalTime.setStyleSheet("color: rgb(255, 255, 255);")
        self.totalTime.setAlignment(QtCore.Qt.AlignCenter)
        self.totalTime.setObjectName("totalTime")
        self.horizontalLayout.addWidget(self.totalTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 50))
        self.groupBox.setMaximumSize(QtCore.QSize(74, 45))
        self.groupBox.setStyleSheet("background-color: rgb(118, 253, 248);\n"
"border-radius:20px;\n"
"padding-left:5px;\n"
"padding-right:5px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.playButton = QtWidgets.QPushButton(self.groupBox)
        self.playButton.setGeometry(QtCore.QRect(30, 10, 80, 29))
        self.playButton.setStyleSheet("background-color: rgb(118, 253, 248);\n"
"border-radius:10px;\n"
"padding-left:5px;\n"
"padding-right:5px;")
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/control-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setObjectName("playButton")
        self.pauseButton = QtWidgets.QPushButton(self.groupBox)
        self.pauseButton.setGeometry(QtCore.QRect(100, 10, 80, 29))
        self.pauseButton.setStyleSheet("background-color: rgb(118, 253, 248);\n"
"border-radius:10px;\n"
"padding-left:5px;\n"
"padding-right:5px;")
        self.pauseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/control-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon1)
        self.pauseButton.setObjectName("pauseButton")
        self.stopButton = QtWidgets.QPushButton(self.groupBox)
        self.stopButton.setGeometry(QtCore.QRect(180, 10, 80, 29))
        self.stopButton.setStyleSheet("background-color: rgb(118, 253, 248);\n"
"border-radius:10px;\n"
"padding-left:5px;\n"
"padding-right:5px;")
        self.stopButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/control-stop-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.volumeLabel = QtWidgets.QLabel(self.centralwidget)
        self.volumeLabel.setText("")
        self.volumeLabel.setPixmap(QtGui.QPixmap("images/speaker-volume.png"))
        self.volumeLabel.setObjectName("volumeLabel")
        self.horizontalLayout_2.addWidget(self.volumeLabel)
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumeSlider.setEnabled(False)
        self.volumeSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.volumeSlider.setStyleSheet("QSlider::groove:horizontal { \n"
"    background-color: white;\n"
"    border: 0px solid #424242; \n"
"    height: 10px; \n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::handle:horizontal { \n"
"    background-color: dark-blue; \n"
"    border: 2px solid rgb(118, 253, 248); \n"
"    width: 16px; \n"
"    height: 20px; \n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius:10px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover { \n"
"    border-radius: 10px;\n"
"}")
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_2.addWidget(self.volumeSlider)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ipmodulePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.ipmodulePushButton.setMinimumSize(QtCore.QSize(200, 40))
        self.ipmodulePushButton.setStyleSheet("background-color: rgb(118, 253, 248);\n"
"font: 10pt \"Trebuchet MS\";\n"
"\n"
"color: rgb(59, 59, 59);\n"
"border-radius:10px;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"font-weight:bold;")
        self.ipmodulePushButton.setObjectName("ipmodulePushButton")
        self.horizontalLayout_3.addWidget(self.ipmodulePushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setStyleSheet("color: rgb(255, 255, 255);")
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.currentTime.setText(_translate("MainWindow", "00:00"))
        self.totalTime.setText(_translate("MainWindow", "00:00"))
        self.ipmodulePushButton.setText(_translate("MainWindow", "Open Image Processing Module"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
